### ISSUE TITLE
Incorrect date format

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#10]
Непонятно в каком формате следует указывать дату рождения. Я ввел в предпочтительном для себя и получил ошибку. 

```
What is your name? Vitaly
Your sex is man or woman? man
What is your height in cm? 169
What is your weight in kg? 69
Укажите дату рождения: 19.09.1999
Exception in thread "main" java.time.format.DateTimeParseException: Text '19.09.1999' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDate.parse(LocalDate.java:400)
	at com.company.Person.setBirthday(Person.java:76)
	at com.company.Main.getUserFromKeyboard(Main.java:92)
	at com.company.Main.main(Main.java:13)
```

**Comment by ibarhatov** [comment]
Лишняя задача, это относится к проверке на ошибки.
