### ISSUE TITLE
Приложение не запускается, FileNotFoundException

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#14]
Приложение не удается запустить - получаю ошибку

```
Exception in thread "main" java.io.FileNotFoundException: /Users/vbarhatov/projects/sandbox/Ivan/HelloWorld/D:/STARS.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.company.FileWorker.read(FileWorker.java:38)
	at com.company.StarPersons.<init>(StarPersons.java:69)
	at com.company.Main.main(Main.java:9)
```

**Comment by ibarhatov** [comment]
Попробуй 274c0ae669408cbdc7e271b808b82eb727f1580f

**Comment by vbarhatov** [comment]
теперь так:
```

Connected to the target VM, address: '127.0.0.1:60465', transport: 'socket'
Exception in thread "main" java.io.FileNotFoundException: /Users/vbarhatov/projects/sandbox/Ivan/HelloWorld/STARS.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.company.FileWorker.read(FileWorker.java:38)
	at com.company.StarPersons.<init>(StarPersons.java:69)
	at com.company.Main.main(Main.java:9)
Disconnected from the target VM, address: '127.0.0.1:60465', transport: 'socket'

Process finished with exit code 1

```

**Comment by vbarhatov** [comment]
Нашел причину. У нас двойная вложенность HelloWorld в HelloWorld. 
```
HelloWorld
  .idea 
  HelloWorld
    .idea
    out
    resources
    src
    test
```

**Comment by vbarhatov** [comment]
Надо ее сократить на один уровень

**Comment by ibarhatov** [comment]
Закрываю
